namespace LottieCppUwpTest
{
    [default_interface]
    runtimeclass MainPage : Windows.UI.Xaml.Controls.Page
    {
        MainPage();
        Int32 MyProperty;

        Windows.Foundation.Collections.IVector<Object> BeforeList{ get; };
        Windows.Foundation.Collections.IVector<Object> AfterList{ get; };
    }
}
